### ISSUE TITLE
Is it possible to add parsing based on json, sqlite?

### ISSUE THREAD

**Issue by BoolmanO** [MostHappyCougar/QACoverageTool#13]
**Hello, I would like to clarify if only 1 xlsx format will be available in the future? 
Would like to have alternatives like json or sqlite**

**Comment by MostHappyCougar** [comment]
Hi, @BoolmanO !
I think there is possible to add other file formats support.
Could you please clarify your purposes? Add some examples of input files?

Thanks, Alejandro

**Comment by MostHappyCougar** [comment]
This issue was closed due to absence of feedback.
